language: c
sudo: false
os:
    - linux

cache:
  directories:
    - $TRAVIS_BUILD_DIR/*/
    - $HOME/.elan
    
before_install:
  - wget http://launchpadlibrarian.net/353523729/libc6_2.23-0ubuntu10_amd64.deb
  - wget http://launchpadlibrarian.net/253728424/libasan1_4.9.3-13ubuntu2_amd64.deb
  - wget http://launchpadlibrarian.net/253728426/libgcc-4.9-dev_4.9.3-13ubuntu2_amd64.deb
  - wget http://launchpadlibrarian.net/253728314/gcc-4.9-base_4.9.3-13ubuntu2_amd64.deb
  - wget http://launchpadlibrarian.net/205680212/libstdc++6_5.1.1-5ubuntu1_amd64.deb
  - wget http://launchpadlibrarian.net/253728432/libstdc++-4.9-dev_4.9.3-13ubuntu2_amd64.deb
  - sudo dpkg --force-breaks -i libc6_2.23-0ubuntu10_amd64.deb
  - sudo dpkg -i gcc-4.9-base_4.9.3-13ubuntu2_amd64.deb
  - sudo dpkg -i libasan1_4.9.3-13ubuntu2_amd64.deb
  - sudo dpkg --force-all -i libgcc-4.9-dev_4.9.3-13ubuntu2_amd64.deb
  - sudo dpkg --force-all -i libstdc++6_5.1.1-5ubuntu1_amd64.deb libstdc++-4.9-dev_4.9.3-13ubuntu2_amd64.deb

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - mkdir $HOME/scripts || echo ""
  - export PATH="$HOME/scripts:$PATH"
  - cp travis_long.sh $HOME/scripts/travis_long
  - chmod +x $HOME/scripts/travis_long
  - (git status | grep  -e "Changes not staged for commit:"); RESULT=$?
  - if [ $RESULT -eq 0 ]; then git checkout -f HEAD ; fi
  - rm `git status | grep "\.lean" | sed "s/\.lean/.olean/"` ||  true
  - rm `git status | grep "\.lean"` || true
  - rm mathlib.txt || true

jobs:
  include:
    - stage: Pre-build-1
      script:
        - travis_long "timeout 2400 leanpkg test" | awk 'BEGIN{e=0;c=-1}c&&--c;/error/{if (!e) {c=30;e=1}};{if (!c) {exit 1}}'

    - stage: Pre-build-2
      script:
        - travis_long "timeout 2400 leanpkg test" | awk 'BEGIN{e=0;c=-1}c&&--c;/error/{if (!e) {c=30;e=1}};{if (!c) {exit 1}}'

    - stage: Test
      script:
        - leanpkg test

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
