[package]
name = "lean-rewrite-search"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "7369ff825a08cb7233fbe7b5ed617ddbca888102"}
libk = {git = "https://github.com/khoek/libk", branch = "master", rev = "461caf0b2915dd612a5e9f4ad7f6b627506d4ec0"}
libiconfig = {git = "https://github.com/khoek/libiconfig", branch = "master", rev = "c3d584f2e88cc75f1c6c0f9786a58bf78a01ac2f"}
