[package]
name = "lean-rewrite-search"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "3ad35223f321e644ef3e16ae9ec5b9383b2baabe"}
libk = {git = "https://github.com/khoek/libk", branch = "master", rev = "461caf0b2915dd612a5e9f4ad7f6b627506d4ec0"}
libiconfig = {git = "https://github.com/semorrison/libiconfig", branch = "master", rev = "e0448efefc194d20c2bfa67545b1ec3d7b467a99"}
