[package]
name = "lean-tidy"
version = "0.1"
lean_version = "khoek/klean:3.4.4"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "120635628368ec261e031cefc6d30e0304088b03"}
libk = {git = "https://github.com/khoek/libk", rev = "f4272b393e47c23d1f97d07a339411ab2cf03f88"}
