[package]
name = "lean-tidy"
version = "0.1"
lean_version = "khoek/klean:3.4.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "6bf879d2c6b974401bcf402746ff3d529e31901b"}
